CREATE TABLE R1 (D INT, A INT);
CREATE TABLE R21 (B INT, C INT, E INT, F INT);
CREATE TABLE R22 (E INT, D INT);
CREATE TABLE F1 (x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));
CREATE TABLE F21 (x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));
CREATE TABLE F22 (x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));
